version: "3"
services:
  app:
    image: logging-demo:latest
    container_name: 'logging-demo'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - '8080:8080'
    volumes:     
    - /mnt/c/store/demo-micrometer-elasticsearch-grafana/logs:/store/demo-micrometer-elasticsearch-grafana/logs
          
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: 'elasticsearch'
    environment:
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "discovery.type=single-node"   
    ports:
    - '9200:9200'
    - '9300:9300'
  grafana:
    image: grafana/grafana:latest
    container_name: 'grafana8'
    ports:
    - '3000:3000'
    volumes:
    - ./monitoring/grafana/:/etc/grafana/
    env_file:
    - ./monitoring/grafana/config.monitoring
    depends_on:
    - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.2.0
    container_name: 'filebeat'
    user: root
    volumes:
      # File must have root permission
      - /home/marco/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /mnt/c/store/demo-micrometer-elasticsearch-grafana/logs:/store/demo-micrometer-elasticsearch-grafana/logs
      - /var/run/docker.sock:/var/run/docker.sock  
    depends_on:
      - elasticsearch  